trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

resources:
  repositories:
    - repository: pipeline_building_blocks
      type: github
      name: 'DFE-Digital/apply-for-postgraduate-teacher-training'
      ref: 'refs/heads/refactor-pipeline'
      endpoint: 'GitHub (DfE-Digital)'

variables:
  debug: true
  imageName: 'apply-for-postgraduate-teacher-training'
  subscriptionPrefix: 's106'
  serviceName: 'apply'
  databaseUsername: 'applyadm512'
    

stages:
- stage: build_test_release
  displayName: 'Build, Test & Release'
  jobs:
  - template: azure-pipelines/azure-pipelines-build-docker-container-job-template.yml@pipeline_building_blocks


- stage: deploy_dev
  displayName: 'Deploy - Development'
  dependsOn: build_test_release
  condition: and(succeeded('build_test_release'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: azure-pipelines/azure-pipelines-deploy-job-template.yml@pipeline_building_blocks
    parameters:
      debug: $(debug)
      subscriptionPrefix: '$(subscriptionPrefix)'
      subscriptionName: 'Apply (106) - Dev'
      environment: 'development'
      resourceEnvironmentName: 'd01'
      serviceName: '$(serviceName)'
      containerImageReference: '$(imageName):$(build.buildNumber)'
      databaseName: '$(serviceName)'
      databaseUsername: '$(databaseUsername)'
      databasePassword: '$(databasePassword)'
      dockerhubUsername: '$(dockerHubUsername)'
      securityKeyBase: '$(secretKeyBase)'


- stage: deploy_test
  displayName: 'Deploy - Test'
  dependsOn: build_test_release
  condition: and(succeeded('build_test_release'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: azure-pipelines/azure-pipelines-deploy-job-template.yml@pipeline_building_blocks
    parameters:
      debug: $(debug)
      subscriptionPrefix: '$(subscriptionPrefix)'
      subscriptionName: 'Apply (106) - Test'
      environment: 'test'
      resourceEnvironmentName: 't01'
      serviceName: '$(serviceName)'
      containerImageReference: '$(imageName):$(build.buildNumber)'
      databaseName: '$(serviceName)'
      databaseUsername: '$(databaseUsername)'
      databasePassword: '$(databasePassword)'
      dockerhubUsername: '$(dockerHubUsername)'
      securityKeyBase: '$(secretKeyBase)'
      

# - stage: deploy_test
#   displayName: 'Deploy - Test'
#   dependsOn: build_test_release
#   condition: and(succeeded('build_test_release'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   jobs:
#   - template: azure-pipelines/azure-pipelines-deploy-job-template.yml@pipeline_building_blocks
#     parameters:
#       debug: $(debug)
#       subscriptionPrefix: '$(subscriptionPrefix)'
#       subscriptionName: 'Apply (106) - Production'
#       environment: 'production'
#       resourceEnvironmentName: 'p01'
#       serviceName: '$(serviceName)'
#       containerImageReference: '$(imageName):$(build.buildNumber)'
#       databaseName: '$(serviceName)'
#       databaseUsername: '$(databaseUsername)'
#       databasePassword: '$(databasePassword)'
#       dockerhubUsername: '$(dockerHubUsername)'
#       securityKeyBase: '$(secretKeyBase)'